#!/usr/bin/env python3
from josh_functions import sum
from josh_functions import array_sum
import sys
import pyperclip


def calc_panel(length, buffer = 10):
    if length < 815 + buffer:
        return [1,0,0,0]
    elif length < 1575 + buffer:
        return [0,1,0,0]
    elif length < 2350 + buffer:
        return [0,0,1,0]
    elif length < 3100 + buffer:
        return [0,0,0,1]
    elif length < (1575 + 2350 + (buffer * 2)):
        return [0,1,1,0]
    elif length < (2350 + 2350 + (buffer * 2)):
        return [0,0,2,0]
    elif length < (2350 + 3100  + (buffer * 2)):
        return [0,0,1,1]
    elif length < (3100 + 3100 + (buffer * 2)):
        return [0,0,0,2]
    else:
        offcut = length % (2350 + buffer)
        if offcut < 750:
            return [0,0,(length // (2350 + buffer))-1,1]
        elif offcut < 1500:
            return [0,0,(length // (2350 + buffer))-2,2]
        elif offcut < (2350 + buffer):
            return [0,0,(length // (2350 + buffer))+1,0]
    raise Exception("The code should never get to this point, calc_panel failure")

def pretty_print(panel_count):
    lengths = [815, 1575, 2350, 3100]
    string_output = ""
    for i in range(4):
        if panel_count[i] == 1:
            string_output += f"{panel_count[i]} Panel at {lengths[i]}\n"
        elif panel_count[i] > 1:
            string_output += f"{panel_count[i]} Panels at {lengths[i]}\n"
    string_output += f"{int(sum(panel_count) * 1.8) + 1} Bags of Rapid Set"
    pyperclip.copy(string_output)
    print(string_output)

def convert_to_mm(string):
    if "m" in string:
        return (int(float(string.replace("m","")) * 1000))

    if ("." in string):
        return (int(float(string) * 1000))
    
    try:
        return int(string)
    except:
        raise Exception("Error converting string to mm")

def main():
    final_panel_count = [0,0,0,0]
    run_length_strings = []
    buffer = 10
    
    all_args = sys.argv[1:]
    while len(all_args) > 0:
        current = all_args.pop(0)
        if current[0] == '-':
            if current == '-b' or '--buffer':
                if len(all_args) > 0:
                    buffer = int(all_args.pop(0))
                    print(f"Buffer is {buffer}mm")
                else:
                    raise Exception("Buffer flag can't be the last argument")
        else:
            run_length_strings.append(current)

    for i in run_length_strings:
        final_panel_count = array_sum(calc_panel(convert_to_mm(i), buffer), final_panel_count)
    pretty_print(final_panel_count)

main()
